/**
 * Agent-scoped model selection shared by runtime entry points.
 * @module @deepseek-ai/dsh-agent/model-selection
 */

import type { Context } from '@deepseek-ai/cordis'
import {
  boundContextSummary,
  createUserMessage,
  type LlmCallConfig,
  type ReasoningEffortId,
} from '@deepseek-ai/dsh-llm'
import { scopeTarget, type Scoped } from '@deepseek-ai/dsh-scope'
import type { Agent, PreStepDecision } from './runtime-types.ts'

/** Complete provider, model, and optional reasoning effort selected for one live Agent. */
export interface ModelSelection {
  /** Registered provider route. */
  provider: string
  /** Provider-owned model id. */
  model: string
  /** Adapter-owned reasoning effort, or provider/default behavior when absent. */
  reasoningEffort?: ReasoningEffortId
}

/** Mutable model selection plus the value captured for the current step. */
export interface ModelSelectionRef {
  /** Model selected for the next step that enters prompt assembly. */
  current: ModelSelection | undefined
  /** Resolved selection published by the latest successful prompt assembly. */
  assembled: ModelSelection | undefined
}

/** Identity-only subject of a model-selection query; no Agent methods are required. */
export interface ModelSelectionQuery {
  /** The exact object used as the selection owner's scope key. */
  readonly owner: object
}

/** One Agent assembly's detached selection before asynchronous routing policy. */
export interface ModelSelectionResolution {
  /** Agent whose route is being resolved. */
  readonly agent: Agent
  /** Configured selection captured before resolution starts. */
  readonly selection: ModelSelection | undefined
  /** Cancellation of this assembly only; absent for callers without a turn signal. */
  readonly signal?: AbortSignal
}

declare module '@deepseek-ai/cordis' {
  interface Events {
    /**
     * Read a detached snapshot without assembling a prompt or consuming a selection.
     * Scope-filtered dispatch uses payload.owner as the routing key.
     * @param payload.owner - exact identity whose current selection is queried.
     * @param next - delegate when this listener owns no current selection.
     * @returns the current selection, or undefined when no owner supplies one.
     * @mode waterfall
     */
    'model-selection/query'(this: Scoped<ModelSelectionQuery>, payload: ModelSelectionQuery, next: () => ModelSelection | undefined): ModelSelection | undefined
    /**
     * Resolve the route for one scoped prompt assembly before its downstream
     * assembly listeners run. The result supplies prompt variables, request
     * routing, and switch notices without changing the configured selection.
     * Scope-filtered dispatch uses payload.agent as the routing key. Diagnostic
     * assemblies without an Agent do not dispatch this event.
     * @param payload.agent - Agent supplied by the assembly context.
     * @param payload.selection - detached configured selection captured before any await.
     * @param payload.signal - cancellation for this assembly, when supplied.
     * @param next - delegate to the captured selection or another resolver.
     * @returns the selection for this assembly, or undefined to retain request defaults.
     * @mode waterfall
     */
    'model-selection/resolve'(this: Scoped<Agent>, payload: ModelSelectionResolution, next: () => Promise<ModelSelection | undefined>): Promise<ModelSelection | undefined>
  }
}

/**
 * Read the configured selection for one scope identity without entering a model
 * turn or running asynchronous resolution. An unresolved policy therefore exposes
 * only its configured fallback here, not a prediction of the next resolved route.
 * @param ctx - context through which to dispatch the scoped query.
 * @param owner - exact object used as the selection owner's scope key.
 * @returns a detached current selection, or undefined when no selection is installed.
 */
export function readModelSelection(ctx: Context, owner: object): ModelSelection | undefined {
  const query: ModelSelectionQuery = { owner }
  return ctx.waterfall(scopeTarget(query, owner), 'model-selection/query', query, () => undefined)
}

function sameRoute(left: ModelSelection, right: ModelSelection): boolean {
  return left.provider === right.provider && left.model === right.model
}

function routeLabel(route: ModelSelection, other: ModelSelection): string {
  return route.provider === other.provider ? route.model : `${route.provider}/${route.model}`
}

function modelSwitchNotice(previous: ModelSelection, selected: ModelSelection) {
  const from = routeLabel(previous, selected)
  const to = routeLabel(selected, previous)
  return createUserMessage({
    content: [{
      type: 'text' as const,
      text: `[model changed: assistant turns above this point were generated by ${from}; the session continues with ${to}]`,
    }],
    source: {
      kind: 'plugin' as const,
      plugin: 'model-selection',
      form: 'notice' as const,
      summary: boundContextSummary(`${from} → ${to}`),
    },
  })
}

/**
 * Couple one mutable selection to Agent-scoped prompt assembly and request routing.
 * Prompt assembly detaches the configured selection before asynchronous
 * `model-selection/resolve` policy runs, then delegates assembly. Only successful,
 * non-cancelled assembly publishes the resolved selection to prompt variables and
 * request routing. Resolution never changes `current`: a concurrent switch takes
 * effect on a later step instead of splitting the two surfaces. Diagnostic
 * assemblies without an Agent retain the configured route without resolution.
 * An absent selected effort clears any inherited effort, restoring the selected
 * model's provider/default behavior.
 *
 * A provider/model change appends a durable user-role notice to the next
 * admitted request. It compares the assembled selection with the latest
 * request header; effort-only changes and empty no-request decisions add no
 * notice. Failure before header persistence repeats the notice on the next
 * request.
 *
 * @param agentCtx - The selected Agent's scoped context.
 * @param selection - Mutable selection owned by the calling entry point.
 * @returns Disposer for all scoped waterfall listeners.
 */
export function installModelSelection(agentCtx: Context, selection: ModelSelectionRef): () => void {
  const disposeSelection = agentCtx.on('model-selection/query', (_payload, next) => {
    const selected = selection.current
    if (selected === undefined) return next()
    return {
      provider: selected.provider,
      model: selected.model,
      ...selected.reasoningEffort === undefined ? {} : { reasoningEffort: selected.reasoningEffort },
    }
  })
  const disposeAssembly = agentCtx.on('system-prompt/assemble', async (_assembly, context, next) => {
    const current = selection.current
    const captured = current === undefined ? undefined : { ...current }
    context.signal?.throwIfAborted()
    const resolved = context.agent === undefined
      ? captured
      : await agentCtx.waterfall(
        scopeTarget(context.agent, context.agent),
        'model-selection/resolve',
        {
          agent: context.agent,
          selection: captured,
          ...context.signal === undefined ? {} : { signal: context.signal },
        },
        () => Promise.resolve(captured),
      )
    context.signal?.throwIfAborted()
    const selected = resolved === undefined ? undefined : { ...resolved }
    const assembled = await next()
    context.signal?.throwIfAborted()
    selection.assembled = selected
    if (selected === undefined) return assembled
    return {
      ...assembled,
      variables: {
        ...assembled.variables,
        provider: selected.provider,
        model: selected.model,
      },
    }
  })
  const disposeRequest = agentCtx.on(
    'agent/request',
    async (_payload, next): Promise<LlmCallConfig> => {
      const resolved = await next()
      const selected = selection.assembled
      if (selected === undefined) return resolved
      const { reasoningEffort: _inheritedEffort, ...withoutInheritedEffort } = resolved
      return {
        ...withoutInheritedEffort,
        provider: selected.provider,
        model: selected.model,
        ...selected.reasoningEffort === undefined
          ? {}
          : { reasoningEffort: selected.reasoningEffort },
      }
    },
  )
  const disposeNotice = agentCtx.on(
    'agent/pre-step',
    async ({ agent, messages, signal, step }, next): Promise<PreStepDecision> => {
      const decision = await next()
      if (decision.kind === 'reject' || signal.aborted) return decision
      // The loop skips an empty first step and an emptied offered continuation.
      if (decision.messages.length === 0 && (step === 1 || messages.length > 0)) return decision
      const selected = selection.assembled
      const previous = agent.session.requestHeader()?.config
      if (selected === undefined || previous === undefined || sameRoute(selected, previous)) return decision
      return { ...decision, messages: [...decision.messages, modelSwitchNotice(previous, selected)] }
    },
    { prepend: true },
  )
  return () => {
    disposeSelection()
    disposeAssembly()
    disposeRequest()
    disposeNotice()
  }
}
