import { describe, expect, it } from 'vitest'
import { Context } from '@deepseek-ai/cordis'
import SystemPrompt from '@deepseek-ai/dsh-system-prompt'
import { createScope } from '@deepseek-ai/dsh-scope'
import {
  agentEvents,
  installModelSelection,
  readModelSelection,
  type Agent,
  type ModelSelection,
  type ModelSelectionRef,
} from '../src/index.ts'
import {
  createUserMessage,
  ReasoningEffortId,
  type LlmCallConfig,
  type UserMessage,
} from '@deepseek-ai/dsh-llm'
import { Session, SessionId } from '@deepseek-ai/dsh-session'

const SIGNAL = new AbortController().signal
const INPUT = createUserMessage({
  content: [{ type: 'text', text: 'continue' }],
  source: { kind: 'user' },
})

function createAgent(): Agent {
  return { session: Session.create(SessionId('model-selection')) } as Agent
}

function expectedNotice(from: string, to: string) {
  return {
    content: [{
      type: 'text',
      text: `[model changed: assistant turns above this point were generated by ${from}; the session continues with ${to}]`,
    }],
    source: { kind: 'plugin', plugin: 'model-selection', form: 'notice', summary: `${from} → ${to}` },
  }
}

async function switchHarness(current: ModelSelection, previous?: ModelSelection) {
  const ctx = new Context()
  await ctx.plugin(SystemPrompt)
  const selection: ModelSelectionRef = { current, assembled: undefined }
  const dispose = installModelSelection(ctx, selection)
  const agent = createAgent()
  if (previous !== undefined) {
    agent.session.append('request/header', { header: { config: previous }, reason: 'initial' })
  }
  await ctx.systemPrompt.assemble()
  return { agent, ctx, dispose, selection }
}

async function preStep(
  ctx: Context,
  agent: Agent,
  {
    messages = [INPUT],
    offered = [INPUT],
    step = 1,
    signal = SIGNAL,
  }: {
    messages?: UserMessage[]
    offered?: UserMessage[]
    step?: number
    signal?: AbortSignal
  } = {},
) {
  return agentEvents(ctx, agent).waterfall(
    'agent/pre-step',
    { turn: 1, step, messages: offered, signal },
    () => Promise.resolve({ kind: 'enter' as const, messages }),
  )
}

describe('installModelSelection()', () => {
  it('reads a detached current selection without assembly or consuming the pending choice', async () => {
    const ctx = new Context()
    await ctx.plugin(SystemPrompt)
    const agent = createAgent()
    const scope = createScope(ctx, agent)
    const selection: ModelSelectionRef = { current: undefined, assembled: { provider: 'old', model: 'old' } }
    const dispose = installModelSelection(scope.ctx, selection)
    const read = () => readModelSelection(scope.ctx, agent)
    try {
      expect(read()).toBeUndefined()
      selection.current = { provider: 'next', model: 'next', reasoningEffort: ReasoningEffortId('low') }
      const snapshot = read()
      expect(snapshot).toEqual(selection.current)
      expect(snapshot).not.toBe(selection.current)
      selection.current.model = 'later'
      expect(snapshot?.model).toBe('next')
      expect(read()?.model).toBe('later')
      expect(selection.assembled).toEqual({ provider: 'old', model: 'old' })
      expect(agent.session.requestHeader()).toBeUndefined()
      dispose()
      expect(read()).toBeUndefined()
    } finally {
      await ctx.fiber.dispose()
    }
  })

  it('isolates selection queries between agent scopes and removes the query on scope disposal', async () => {
    const ctx = new Context()
    await ctx.plugin(SystemPrompt)
    const a = createAgent()
    const b = createAgent()
    const scopeA = createScope(ctx, a)
    const scopeB = createScope(ctx, b)
    installModelSelection(scopeA.ctx, { current: { provider: 'a', model: 'a' }, assembled: undefined })
    installModelSelection(scopeB.ctx, { current: { provider: 'b', model: 'b' }, assembled: undefined })
    const read = (agent: Agent) => readModelSelection(ctx, agent)
    try {
      expect(read(a)).toEqual({ provider: 'a', model: 'a' })
      expect(read(b)).toEqual({ provider: 'b', model: 'b' })
      await scopeA.dispose()
      expect(read(a)).toBeUndefined()
      expect(read(b)).toEqual({ provider: 'b', model: 'b' })
    } finally {
      await ctx.fiber.dispose()
    }
  })

  it('snapshots prompt variables and request routing together, then disposes its listeners', async () => {
    const ctx = new Context()
    await ctx.plugin(SystemPrompt)
    const selection: ModelSelectionRef = { current: undefined, assembled: undefined }
    const dispose = installModelSelection(ctx, selection)
    const agent = createAgent()
    const seed: LlmCallConfig = { provider: 'seed', model: 'seed', temperature: 0.2 }
    const signal = new AbortController().signal

    expect((await ctx.systemPrompt.assemble()).variables).toEqual({})
    await expect(agentEvents(ctx, agent).waterfall(
      'agent/request', { turn: 1, step: 0, signal }, () => Promise.resolve(seed),
    )).resolves.toBe(seed)

    selection.current = {
      provider: 'alpha',
      model: 'a1',
      reasoningEffort: ReasoningEffortId('high'),
    }
    expect((await ctx.systemPrompt.assemble()).variables).toMatchObject({ provider: 'alpha', model: 'a1' })
    selection.current = { provider: 'beta', model: 'b1' }
    await expect(agentEvents(ctx, agent).waterfall(
      'agent/request', { turn: 1, step: 0, signal }, () => Promise.resolve(seed),
    )).resolves.toEqual({
      provider: 'alpha',
      model: 'a1',
      reasoningEffort: ReasoningEffortId('high'),
      temperature: 0.2,
    })

    expect((await ctx.systemPrompt.assemble()).variables).toMatchObject({ provider: 'beta', model: 'b1' })
    const inherited: LlmCallConfig = {
      provider: 'alpha',
      model: 'a1',
      reasoningEffort: ReasoningEffortId('max'),
      temperature: 0.2,
    }
    await expect(agentEvents(ctx, agent).waterfall(
      'agent/request', { turn: 1, step: 1, signal }, () => Promise.resolve(inherited),
    )).resolves.toEqual({ provider: 'beta', model: 'b1', temperature: 0.2 })

    dispose()
    expect((await ctx.systemPrompt.assemble()).variables).toEqual({})
    await expect(agentEvents(ctx, agent).waterfall(
      'agent/request', { turn: 2, step: 0, signal }, () => Promise.resolve(seed),
    )).resolves.toBe(seed)
    await ctx.fiber.dispose()
  })

  it('announces same-provider and cross-provider route changes from the assembled selection', async () => {
    const { agent, ctx, dispose, selection } = await switchHarness(
      { provider: 'alpha', model: 'a1' },
      { provider: 'alpha', model: 'a0' },
    )
    await expect(preStep(ctx, agent)).resolves.toMatchObject({
      messages: [INPUT, expectedNotice('a0', 'a1')],
    })

    selection.current = { provider: 'beta', model: 'b1' }
    await ctx.systemPrompt.assemble()
    selection.current = { provider: 'alpha', model: 'a2' }
    await expect(preStep(ctx, agent)).resolves.toMatchObject({
      messages: [INPUT, expectedNotice('alpha/a0', 'beta/b1')],
    })
    await ctx.systemPrompt.assemble()
    await expect(preStep(ctx, agent)).resolves.toMatchObject({
      messages: [INPUT, expectedNotice('a0', 'a2')],
    })

    dispose()
    await ctx.fiber.dispose()
  })

  it('does not announce initial, same-route, effort-only, rejected, aborted, or disposed steps', async () => {
    const { agent, ctx, dispose, selection } = await switchHarness({ provider: 'alpha', model: 'a0' })
    await expect(preStep(ctx, agent)).resolves.toMatchObject({ kind: 'enter', messages: [INPUT] })
    agent.session.append('request/header', {
      header: { config: { provider: 'alpha', model: 'a0' } }, reason: 'initial',
    })
    selection.current = {
      provider: 'alpha',
      model: 'a0',
      reasoningEffort: ReasoningEffortId('high'),
    }
    await ctx.systemPrompt.assemble()
    await expect(preStep(ctx, agent)).resolves.toMatchObject({ kind: 'enter', messages: [INPUT] })

    selection.current = { provider: 'alpha', model: 'a1' }
    await ctx.systemPrompt.assemble()
    const rejected = await agentEvents(ctx, agent).waterfall(
      'agent/pre-step',
      { turn: 1, step: 1, messages: [], signal: SIGNAL },
      () => Promise.resolve({ kind: 'reject' as const }),
    )
    expect(rejected).toEqual({ kind: 'reject' })
    const aborted = new AbortController()
    aborted.abort()
    await expect(preStep(ctx, agent, { signal: aborted.signal })).resolves.toMatchObject({ messages: [INPUT] })

    dispose()
    await expect(preStep(ctx, agent)).resolves.toMatchObject({ kind: 'enter', messages: [INPUT] })
    await ctx.fiber.dispose()
  })

  it('preserves empty no-call decisions and announces an empty tool continuation', async () => {
    const { agent, ctx } = await switchHarness(
      { provider: 'alpha', model: 'a1' },
      { provider: 'alpha', model: 'a0' },
    )
    await expect(preStep(ctx, agent, { messages: [] })).resolves.toEqual({ kind: 'enter', messages: [] })
    await expect(preStep(ctx, agent, { messages: [], step: 2 })).resolves.toEqual({ kind: 'enter', messages: [] })
    await expect(preStep(ctx, agent, { messages: [], offered: [], step: 2 })).resolves.toMatchObject({
      messages: [{ source: { summary: 'a0 → a1' } }],
    })
    await ctx.fiber.dispose()
  })
})
